### PR TITLE
Fix windows

### LINKED ISSUE #10: fail on windows
version 1.x was working fine for me
After a migration to babel@6 and update of this package

It's just because it's returning `/` instead of '\'
PR is on its way ;)

### PR DESCRIPTION
**Pull request by mastilver**
I couldn't make the test fail on linux, so we won't know if in the future a commit introduce a windows related bug

closes #10 

Good to be merged ;)

### CODE REVIEW

**Comment by michaelzoidl** [comment]
Awesome :) 
I try to test it the next few days - if osx has no problem i will merge this and release it instant :) 

Thanks

**Comment by mastilver** [comment]
@michaelzoidl any update?

**Comment by mastilver** [comment]
@michaelzoidl ping

**Comment by michaelzoidl** [comment]
Better now than never.. :) 
Sorry for the.. i don't know.. is delay the right word? 

Anyway, i merged your PR :) 
Seem's like your PR is at this moment the only build who doesn't fail.. anything changed on the system.. 

So, big thank you!

**Pull request merged**
