### PR TITLE
Add ESLint rule

### PR DESCRIPTION
**Pull request by yinanfang**
Pull request for #22

### CODE REVIEW

**Comment by yinanfang** [comment]
I only changed the README. It seems like the test failed because of some windows issue.

**Comment by michaelzoidl** [comment]
Thats some issue from npm, just checked that out... i moved on to node version 5, seem's like that still works like a charm.

You're PR has the travis-config with the failing stuff... do you want open a new PR or should i add that by myself into the readme?

**Comment by yinanfang** [comment]
I just created a new pull request. It's my second time contributing. I'm still enjoying the process😬

**Comment by jasan-s** [comment]
After adding this rule I now get the error Missing file extension (import/extensions)

**Pull request closed without merging**
