### PR TITLE
specify root folder

### PR DESCRIPTION
**Pull request by degr**

### CODE REVIEW

**Comment by michaelzoidl** [comment]
Awesome... seems like the tests are failing because there is no `rootPathSuffix` given.
Just make a little `if` for the `rootPathSuffix ` in the [transformRelativeToRootPath](https://github.com/michaelzoidl/babel-root-import/pull/8/files#diff-d2af2111c9784b269a5e2bebc4b7adb5R9).
Then the tests should pass.

Then for the new feature we should add a new test in the [Plugin-Test](https://github.com/michaelzoidl/babel-root-import/blob/master/test/plugin.spec.js).
It's more or less copy&paste... we just have to specify a babelrc in the test...

**Comment by michaelzoidl** [comment]
Okay wait... just fixed it was no big deal.. i merge this and update it by myself :)

**Comment by michaelzoidl** [comment]
Ok, i merged your changes and fixed the tests / added new tests :)
You're awesome... thanks.

Now i'm updating the npm package \o/

**Comment by degr** [comment]
I see, thanks

**Pull request merged**
