### PR TITLE
fix windows

### PR DESCRIPTION
**Pull request by mastilver**
closes: #10

### CODE REVIEW

**Comment by mastilver** [comment]
trying to make it fail on the server without any success...

**Comment by michaelzoidl** [comment]
Yay nice dude :)

**Comment by mastilver** [comment]
Noooo...
I should have make it more clear, I was just trying to make the ci server fail before I can fix the issue
The issue is not fixed, I will try to work more on that tonight

**Comment by michaelzoidl** [comment]
Well...  I thought you fixed it, sorry.
But it's not published in npm, so no problem, if you fix it in the next few days its okay, if not then i revert the changes.

**Comment by michaelzoidl** [comment]
You can make a new PR .. i don't merge it, i swear.

**Comment by mastilver** [comment]
Cool :D

**Pull request merged**
